# use AWS CloudFormation to create a stack that includes the Lambda function and the API Gateway endpoint.
# use YAML format to define the CloudFormation stack.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: my-lambda-function.zip
      Handler: lambda_function.lambda_handler
      Role: my-lambda-role
      Runtime: python3.8
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: my-rest-api
  MyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyApiGateway.RootResourceId
      PathPart: my-resource
      RestApiId: !Ref MyApiGateway
  MyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      AuthorizationType: NONE
      RestApiId: !Ref MyApiGateway
      ResourceId: !Ref MyResource
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
  MyDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: MyMethod
    Properties
